---
- name: Copy the wiki dump
  copy:
    src: wiki.xml
    dest: "{{ flamestream_dir }}/wiki.xml"

- name: Copy the deployer file
  template:
    src: deployer.conf.j2
    dest: "{{ flamestream_dir }}/deployer.conf"

- name: Copy the bench configuration file
  template:
    src: bench.conf.j2
    dest: "{{ flamestream_dir }}/bench.conf"

- name: Start the flamestream bench
  shell: >
    java -Xms500m -Xmx500m -XX:+PrintGC -XX:+PrintGCDetails -XX:+HeapDumpOnOutOfMemoryError
    -cp '{{ flamestream_dir }}/lib/*'
    com.spbsu.flamestream.example.benchmark.BenchStand
    {{ flamestream_dir }}/bench.conf {{ flamestream_dir }}/deployer.conf > {{ flamestream_dir }}/bench.log 2>&1

- name: Fetch bench logs
  fetch:
    src: "{{ flamestream_dir }}/bench.log"
    dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flamestream/bench.log
    flat: true

- name: Fetch latencies
  fetch:
    src: /tmp/lat.data
    dest: results/{{ lookup("pipe", "git rev-parse --short HEAD") }}/{{ groups['workers'] | length }}/{{ rate }}/flamestream/latency/lat.data
    flat: true
