---
- name: Install common packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jdk
    - rsync
    - vim
    - less
    - htop
    - procps
    - unzip
    - sysstat
    - make
    - gcc
