---
- name: Create zookeeper dir exists
  file:
    path: "{{ zookeeper_dir }}"
    state: directory

- name: Create tarball dir
  file:
    path: "{{ zookeeper_tarball_dir }}"
    state: directory

- name: Download ZK tarball
  get_url: 
    url: "{{ zookeeper_url }}"
    dest: "{{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz"

- name: Unpack the tarball
  command: tar -xf {{ zookeeper_tarball_dir }}/zookeeper-{{ zookeeper_version }}.tar.gz --strip-components=1
  args: 
    chdir: "{{ zookeeper_dir }}" 
    creates: "{{ zookeeper_dir }}/bin"

- name: Configure the zookeeper
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_dir }}/conf/zoo.cfg"

- name: Restart zk
  shell: "{{ zookeeper_dir }}/bin/zkServer.sh restart"

- name: Clean graphs
  shell: "{{ zookeeper_cli }} rmr /graphs"

- name: Clean configs
  shell: "{{ zookeeper_cli }} rmr /config"
