---
all:
  children:
    manager:
      hosts:
        worker1:
    acker:
      hosts:
        worker1:
    bench:
      hosts:
        worker2:
    input:
      hosts:
        worker1:
    workers:
      hosts:
        worker1:
        worker2:
  vars:
    ansible_user: root
    ansible_connection: docker
